# Generated by Django 3.0.8 on 2020-09-17 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AQIPrediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t', models.IntegerField()),
                ('tm1', models.IntegerField()),
                ('tm', models.IntegerField()),
                ('slp', models.IntegerField()),
                ('h', models.IntegerField()),
                ('vv', models.IntegerField()),
                ('v', models.IntegerField()),
                ('vm', models.IntegerField()),
            ],
        ),
    ]
